### ISSUE TITLE
Happy New Year + a tiny problem :(

### ISSUE THREAD

**Issue by buschmann** [jvdweerthof/net.hlktech.relay#76]
Hihoo, 
i run some of this cards, and normal i love them++ :)
BUT
Is there any way to set the wifi-module back to factory default by connecting "any" PIN`s manually, without using the "serial_port"..?!?

**Comment by jvdweerthof** [comment]
Happy to see I'm not the only user ;-)

https://www.manualslib.com/manual/2048357/Hi-Link-Hlk-Sw16.html?page=6#manual

Have a look at the manual, it describes pushing a button for 6 seconds to do a factory reset.  Although I'm not sure where exactly this button is supposed to be.

**Comment by buschmann** [comment]
THX sounds good.
BUT this is not for resetting the wifi-module.
This is RST for the APP.. :(
I am looking for a reset pin for the wifi-router-module itself.
Here for the same as here but of course for the 16-chan..

My module does not start with the normal "led-lights"
Only green big led is blinking and on module only red is ON.
No blue, and no others... .. :((

[image: image.png]



Am Mo., 3. Jan. 2022 um 22:56 Uhr schrieb Jochem ***@***.***>:

**Comment by jvdweerthof** [comment]
Page 8 of the manual for the wifi-module may help you:
https://www.prometec.net/wp-content/uploads/2015/01/HLK-RM04-user-manual.pdf
>3.1 Restore factory settings
In order to ensure that all of configuration process is correct, bringing the module to restore
the factory settings firstly. Factory mode, the module can skip this step. Above 5V (500mA) to
power the module on the power, wait about 2.5 minutes for the system to start, after the start
completion, pulled ES / RST pin down and make it surpass Trst, release ES / RST pin, the system
will automatically restart. After rebooting, the system is already in Factory mode.

**Comment by buschmann** [comment]
I thought so too, and normal YESS ..this is the way... ,))
BUT _ IF  this doesn't work THAN i can do what?  :((

https://amoc.info/tim/redlightwifimodulenorstfunction.mp4



Am Di., 4. Jan. 2022 um 21:07 Uhr schrieb Jochem ***@***.***>:

**Comment by jvdweerthof** [comment]
That's too bad. Unfortunately I have no idea what else you could try.

I'm just a user of the device that decided to develop this integration for Homey as it was missing, but I have no idea how the device itself actually works. I think your best bet is to try and contact the support of hlktech/hi link.

**Comment by buschmann** [comment]
... the hlk support is not same cool as the products.. :(
but as nerd i never give up ;)
